name: lotr_drinking_game
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  go_router: ^8.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^1.4.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo/
