name: lotr_drinking_game
description: Fellowship of the Drink
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_performance: ^0.9.2+3
  firebase_remote_config: ^4.2.3
  fl_chart: ^0.63.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  go_router: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  logger: ^1.4.0
  rflutter_alert: ^2.0.7
  rxdart: ^0.27.7
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

dependency_overrides:
  wakelock:
    git:
      url: https://github.com/davidmartos96/wakelock
      path: wakelock
      ref: update
  wakelock_macos:
    git:
      url: https://github.com/davidmartos96/wakelock
      path: wakelock_macos
      ref: update
  wakelock_platform_interface:
    git:
      url: https://github.com/davidmartos96/wakelock
      path: wakelock_platform_interface
      ref: update
  wakelock_web:
    git:
      url: https://github.com/davidmartos96/wakelock
      path: wakelock_web
      ref: update
  wakelock_windows:
    git:
      url: https://github.com/davidmartos96/wakelock
      path: wakelock_windows
      ref: update 

flutter_icons:
  ios: true
  android: true
  web:
    generate: true
    image_path: "assets/images/logo/logo.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  image_path_android: "assets/images/logo/logo.png"
  image_path_ios: "assets/images/logo/logo-launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/
    - assets/images/characters/
