// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PXdYEPdRd7BEvmcIrSFb91PCgbbAJY0',
    appId: '1:668643921360:web:ca536e3ee23bf8c68cfdd5',
    messagingSenderId: '668643921360',
    projectId: 'lotr-drinking-game',
    authDomain: 'lotr-drinking-game.firebaseapp.com',
    storageBucket: 'lotr-drinking-game.appspot.com',
    measurementId: 'G-XKJM2LXLEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpWKq_K80N3EaE7PmzkGCGDPjEcUl1U2k',
    appId: '1:668643921360:android:6780eda95b60741b8cfdd5',
    messagingSenderId: '668643921360',
    projectId: 'lotr-drinking-game',
    storageBucket: 'lotr-drinking-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXNF9nsqcwVW8cQ9ixyVKGG8JOu2g3dd8',
    appId: '1:668643921360:ios:ff9b6e30d122ffa58cfdd5',
    messagingSenderId: '668643921360',
    projectId: 'lotr-drinking-game',
    storageBucket: 'lotr-drinking-game.appspot.com',
    iosClientId: '668643921360-fmh0j7st0jpb1mkeipeh726f1jrl7r4i.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotrDrinkingGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXNF9nsqcwVW8cQ9ixyVKGG8JOu2g3dd8',
    appId: '1:668643921360:ios:ee75b527e7d2a08a8cfdd5',
    messagingSenderId: '668643921360',
    projectId: 'lotr-drinking-game',
    storageBucket: 'lotr-drinking-game.appspot.com',
    iosClientId: '668643921360-jc2ishkl7i0h8u6gkshon4ft87nk0o5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.lotrDrinkingGame.RunnerTests',
  );
}
