name: Deploy to Firebase Hosting and Firebase App Distribution
on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # you can switch between 'stable', 'beta', 'dev', and 'master'

      # Parallel steps for building web and apk
      - name: Build web
        run: flutter build web

      - name: Build apk
        run: flutter build apk

      # Deploy to Firebase
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOTR_DRINKING_GAME }}"
          channelId: live
          projectId: lotr-drinking-game
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

      - name: Upload android to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:668643921360:android:6780eda95b60741b8cfdd5
          serviceCredentialsFileContent: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOTR_DRINKING_GAME }}"
          groups: android
          file: build/app/outputs/flutter-apk/app-release.apk
